# Generated by Django 5.2.5 on 2025-12-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='payment_id',
            new_name='session_id',
        ),
    ]
